### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by mrakitin** [klauer/recordwhat#12]
@klauer, do you mind to include a license file into the repo? We are trying to conda-package it with @jklynch (https://github.com/NSLS-II/lightsource2-recipes/issues/153). Thanks!

**Comment by klauer** [comment]
I think this project is pretty much used by no-one... you might want to revisit your requirements...

That said, I have no issues with putting up a BSD 3-clause license file.

**Comment by mrakitin** [comment]
Maybe we will use it at NSLS-II. Will package first and see how useful it is. Thanks for taking care of the license file!

**Comment by mrakitin** [comment]
Thank you, @klauer!
